"""HawkPhish - Anti-Detection Headers & Randomization"""
import random
import socket
import time
from datetime import datetime, timedelta
from typing import Dict, List

# User-Agent pools for email clients
OUTLOOK_UAS = [
    "Microsoft Outlook 16.0.16731.20170",
    "Microsoft Outlook 16.0.16631.20148",
    "Microsoft Outlook 16.0.16529.20154",
    "Microsoft Outlook 16.0.16327.20200",
]

THUNDERBIRD_UAS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Thunderbird/128.0",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:115.0) Gecko/20100101 Thunderbird/115.0",
]

APPLE_MAIL_UAS = [
    "Apple Mail (2.3654.80.0.1.18)",
    "Apple Mail (2.3654.100.0.2.22)",
]

GMAIL_UAS = [
    "Gmail (2.0.0.0)",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
]

# Random timezone offsets
TIMEZONE_OFFSETS = ["+0000", "+0100", "+0200", "+0300", "-0500", "-0800", "+0530", "+0900"]

# Random email client names
X_MAILERS = [
    "Microsoft Outlook 16.0",
    "Mozilla Thunderbird 115.0",
    "Apple Mail (2.3654.80.0.1.18)",
    "Mail.app (2.0)",
    "Microsoft Outlook Express 6.0",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    "Windows Live Mail 16.4.3528.331",
    "Roundcube Webmail/1.6.0",
]

# Random MIME versions
MIME_VERSIONS = ["1.0", "1.0 (Mac OS X Mail 16.0)", "1.0 (Apple Message framework v1284)", "1.0 (Generated by SMTP2GO v2.0)"]

# Random priority values
PRIORITIES = ["1", "3", "5"]
IMPORTANCE = ["high", "normal", "low"]

# Random envelope-from domains
ENVELOPE_DOMAINS = [
    "outlook.com", "gmail.com", "yahoo.com", "protonmail.com",
    "icloud.com", "hotmail.com", "live.com", "aol.com",
]

# Microsoft Exchange specific headers
EXCHANGE_HEADERS = [
    "X-MS-Exchange-Organization-AuthAs",
    "X-MS-Exchange-Organization-AuthSource",
    "X-MS-Exchange-Organization-AuthMechanism",
    "X-MS-Exchange-Organization-BypassClutter",
    "X-MS-Exchange-Organization-MessageDirectionality",
    "X-MS-Exchange-Organization-SCL",
    "X-MS-Exchange-Organization-PCL",
    "X-MS-Has-Attach",
    "X-MS-TNEF-Correlator",
    "X-MS-Exchange-Organization-RecordReviewCfmType",
]


def get_random_ua() -> str:
    """Get a random email client user agent."""
    pool = random.choice([OUTLOOK_UAS, THUNDERBIRD_UAS, APPLE_MAIL_UAS, GMAIL_UAS])
    return random.choice(pool)


def get_random_mailer() -> str:
    """Get random X-Mailer header value."""
    return random.choice(X_MAILERS)


def get_random_timezone() -> str:
    """Get random timezone offset string."""
    return random.choice(TIMEZONE_OFFSETS)


def get_random_envelope_from(sender_domain: str) -> str:
    """Generate a random envelope from address."""
    prefixes = ["noreply", "no-reply", "mailer-daemon", "postmaster", "bounce", "mail"]
    prefix = random.choice(prefixes)
    return f"{prefix}@{sender_domain}"


def add_anti_detection_headers(msg, domain: str, sender_email: str, provider: str = "custom"):
    """Add randomized headers to avoid spam filter detection."""
    # Randomize User-Agent
    msg["User-Agent"] = get_random_ua()
    
    # Randomize X-Mailer
    msg["X-Mailer"] = get_random_mailer()
    
    # Randomize MIME version
    msg["MIME-Version"] = random.choice(MIME_VERSIONS)
    
    # Randomize priority
    msg["X-Priority"] = random.choice(PRIORITIES)
    msg["X-MSMail-Priority"] = random.choice(IMPORTANCE).capitalize()
    msg["Importance"] = random.choice(IMPORTANCE).capitalize()
    
    # Random date variation (within 2 hours of now)
    offset_mins = random.randint(-120, 120)
    randomized_date = datetime.utcnow() + timedelta(minutes=offset_mins)
    msg["Date"] = randomized_date.strftime('%a, %d %b %Y %H:%M:%S %z')
    
    # Random envelope-from
    msg["X-Envelope-From"] = get_random_envelope_from(domain)
    
    # Random Microsoft Exchange headers (if it looks like corporate)
    if provider in ["office365", "microsoft_365", "outlook"]:
        msg["X-MS-Exchange-Organization-AuthAs"] = "Internal"
        msg["X-MS-Exchange-Organization-AuthSource"] = random.choice([
            "DM5PR12MB4304.namprd12.prod.outlook.com",
            "CO1PR11MB4880.namprd11.prod.outlook.com",
            "SN7PR12MB5496.namprd12.prod.outlook.com",
        ])
        msg["X-MS-Exchange-Organization-AuthMechanism"] = "04"
        msg["X-MS-Exchange-Organization-SCL"] = "-1"
        msg["X-MS-Exchange-Organization-PCL"] = "2"
    
    # Random Thread-Index for conversation threading
    msg["Thread-Index"] = "".join([random.choice("ABCDEF0123456789") for _ in range(48)])
    
    # Random Content-ID base
    msg["X-Content-ID"] = f"<{random.choice('abcdef')}{random.randint(100000,999999)}@{domain}>"
    
    # Random bounce address
    msg["Return-Path"] = get_random_envelope_from(domain)
    
    # Random sender IP
    msg["X-Originating-IP"] = f"[{random.randint(10,99)}.{random.randint(10,99)}.{random.randint(10,99)}.{random.randint(10,99)}]"
    
    # Random transport info
    msg["X-Transport"] = random.choice([
        "SMTP; DM5PR12MB4304.namprd12.prod.outlook.com",
        "SMTP; CO1PR11MB4880.namprd11.prod.outlook.com",
        "SMTP; mail.google.com",
        "ESMTPS; mail.example.com",
    ])
    
    # Random session ID
    msg["X-Session-ID"] = "".join([random.choice("abcdef0123456789") for _ in range(32)])
    
    # Random delivery priority
    msg["X-MS-Priority"] = random.choice(["1", "3", "5"])
    
    # Random header order randomization (simulated by extra headers)
    msg["X-Campaign-ID"] = "".join([random.choice("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789") for _ in range(12)])
    
    # Random source tracking
    msg["X-Source"] = random.choice(["web", "desktop", "mobile", "api", "crm", "automation"])
    
    return msg
